// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6Pzb43BcTFxtBuqy_P0m98NqcMAYkUE',
    appId: '1:556264325685:web:ffc7c41e6d3d3967f0277c',
    messagingSenderId: '556264325685',
    projectId: 'lost-and-found-407a8',
    authDomain: 'lost-and-found-407a8.firebaseapp.com',
    storageBucket: 'lost-and-found-407a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1B1_uNHAL2ogMkKBVux9Qw9wwZlrNsRo',
    appId: '1:556264325685:android:688a79714f903496f0277c',
    messagingSenderId: '556264325685',
    projectId: 'lost-and-found-407a8',
    storageBucket: 'lost-and-found-407a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZtwHtolKIFZ5KJfnF-KA7jBMRWlGdAQ',
    appId: '1:556264325685:ios:5f51a9af181044fcf0277c',
    messagingSenderId: '556264325685',
    projectId: 'lost-and-found-407a8',
    storageBucket: 'lost-and-found-407a8.appspot.com',
    iosClientId: '556264325685-ro77gbdhnub9p8bvbcmnbgih325sdk19.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsZtwHtolKIFZ5KJfnF-KA7jBMRWlGdAQ',
    appId: '1:556264325685:ios:5f51a9af181044fcf0277c',
    messagingSenderId: '556264325685',
    projectId: 'lost-and-found-407a8',
    storageBucket: 'lost-and-found-407a8.appspot.com',
    iosClientId: '556264325685-ro77gbdhnub9p8bvbcmnbgih325sdk19.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostandfound',
  );
}
